var Controller = require('./controller'); //Static = require(./static);

exports.endpoints = [
	
	// Endpoint for home
	{	method: 'GET',
		path: '/',
		config: Controller.getHome
	},

	// Endpoint to get static files.
	{
		method: 'GET',
		path: '/view/{static*}',
		config: Controller.getStatic
	},

	// Endpoint to login
	{
		method: 'POST',
		path: '/login',
		config: Controller.login
	},

	// Endpoint to sign up
	{
		method: 'POST',
		path: '/register',
		config: Controller.register
	},

	// Endpoint to confirm email
	// This endpoint is generated by appy (with a querystring at the end). The actual endpoint to activate a user using appy is
	// /register/activate.
	{
		method: 'GET',
		path: '/user/activate',
		config: Controller.verifyEmail
	}
];
